name: Cypress CI

on:
  push:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: planeta-qa-e2e
        run: npm install

      - name: Verify Cypress
        working-directory: planeta-qa-e2e
        run: npx cypress verify

      - name: Run Cypress tests
        working-directory: planeta-qa-e2e
        run: npx cypress run