name: Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start Spring Boot API
        run: |
          cd planeta-qa
          ./mvnw spring-boot:run &
          sleep 20

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cypress dependencies
        run: |
          cd planeta-qa-e2e
          npm install

      - name: Run Cypress tests
        run: |
          cd planeta-qa-e2e
          npx cypress run